---
- name: Download Redis
  get_url:
    url: http://download.redis.io/releases/redis-3.2.8.tar.gz
    dest: /usr/share/redis/redis-3.2.8.tar.gz
  become: yes

- unarchive:
    src: /usr/share/redis/redis-3.2.8.tar.gz
    dest: /usr/share/redis

- make:
    chdir: /usr/share/redis/redis-3.2.8
  
- make:
    chdir: /usr/share/redis/redis-3.2.8
    target: install
  become: yes

- script: /usr/share/redis/redis-3.2.8/install_server.sh
  become: yes

- name: Starting Redis service
  service:
    name: redis_6379.service
    state: started