---
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

- name: Enable Elasticsearch service
  service:
    name: elasticsearch.service
    state: started

- name: Config file for Elasticsearch
  template:
    src: ../templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch

- name: Restart Elasticsearch service
  service:
    name: elasticsearch.service
    state: restarted
