---
- name: Install Elastic public key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
    
- name: Update repositories cache and install apt-transport-https package
  apt:
    name: apt-transport-https
    state: latest

- name: Save the repository definition
  shell: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
